# Generated by Django 6.0 on 2025-12-11 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Skill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Job",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=300)),
                ("company", models.CharField(blank=True, max_length=200, null=True)),
                ("location", models.CharField(blank=True, max_length=150, null=True)),
                (
                    "salary_text",
                    models.CharField(blank=True, max_length=120, null=True),
                ),
                ("salary_min", models.FloatField(blank=True, null=True)),
                ("salary_max", models.FloatField(blank=True, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("url", models.URLField(blank=True, max_length=500, null=True)),
                ("posted_date", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "skills",
                    models.ManyToManyField(
                        blank=True, related_name="jobs", to="api.skill"
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
